### PR TITLE
remove languageCode in TNF_WELL_KNOWN

### PR DESCRIPTION
**Pull request by hasanbasri1993**
i suggest to remove this, because it will add a languageCode to payload.
i reference to NFC Tool, gototags

### CODE REVIEW

**Comment by semlette** [comment]
Isn't this exactly what the `.data` field on `NDEFRecord` does?

**Comment by hasanbasri1993** [comment]
just enough add languageCode in `payload`, no need in `data`

**Comment by semlette** [comment]
In my first reply I had misunderstood what you were trying to do.

You can remove the language code by calling `NDEFRecord.text` with the `languageCode` argument set to an empty string.
nfc_in_flutter versions before 2.0.4 (released today) accidentally ignored the `languageCode` argument, but it should be working fine now.

I am closing the PR as the functionality can be accomplished using the `languageCode` argument of `NDEFRecord.text`.

**Comment by hasanbasri1993** [comment]
hhmm be ugly ...
i tried  `return NDEFRecord.text(record.payloadController.text, languageCode: "");` 
image

should be like this
image

**Comment by semlette** [comment]
The NDEF specification requires that a well-known text record begins with
- a byte that specifies how long the language code is
- a language code
- the payload itself.

The Android code that constructs the `NdefMessage` *is* correct, however the Flutter part that constructs the `Map` the `NdefMessage` is constructed from, is not. The 2.0.3 release did *not* fix the issue as you said, however neither will your PR (not completely anyway).
The language code is being inserted incorrectly, as it is concatenated with the payload ([line 378 of `api.dart`](https://github.com/semlette/nfc_in_flutter/blob/bd6ae1e08a7dd98ec38f5050cbcd4caa9ef0ab77/lib/src/api.dart#L378) as you said as well). 
When `NDEFRecord._toMap` was called, it didn't set the [language code in `languageCode`](https://github.com/semlette/nfc_in_flutter/blob/7dfb83c65f43c690c3cc007b12d09687ec186fc0/lib/src/api.dart#L447), which would cause the Android code to [set the language code to `en`](https://github.com/semlette/nfc_in_flutter/blob/d0175c4f9417297575f37ea3ff8ab5e41b8c233d/android/src/main/java/me/andisemler/nfc_in_flutter/NfcInFlutterPlugin.java#L459), which wouldn't be the correct language code.

Your PR would have solved the problem, if the `languageCode` given to `NDEFRecord.text` is always 2 characters long. However the first byte (the language length byte, I call it the status byte) would be incorrect if the language code is not 2 characters long. Because `languageCode` was not set in the `NDEFRecord._toMap` `Map`, the language code would default to `en` which would set the status byte to signal the language code will be 2 characters long. If you were then to set the `languageCode` argument to an empty string or something not 2 characters, it would still signal the language code is 2 characters long.
The same problem would also occur on iOS.

I have reverted the changes I made in v2.0.3 and tried to fix them in the [`languagecode-fix` branch](https://github.com/semlette/nfc_in_flutter/tree/languagecode-fix). Please see if that fixes the issue.

**Comment by semlette** [comment]
I have done a lot of tests on the `languagecode-fix` branch and confirmed that it fixes the issue.
I will be merging it to `master` and it will be in the next release.

**Pull request closed without merging**
